camera:
  width: 640
  height: 480

processing:
  roi: [0, 0, 640, 480]  # set to your region of interest
  threshold: 128
  min_area: 50

logging:
  level: INFO

events:
  roi: [0, 0, 640, 480]
  diff_threshold: 25
  min_event_area: 500
  debounce_frames: 10

mysql:
  host: 127.0.0.1
  port: 3306
  user: your_user
  password: your_password
  database: connectvision
  table: events
